/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as SystemSplashRouteImport } from './routes/system.splash'
import { Route as SystemMaintenanceRouteImport } from './routes/system.maintenance'
import { Route as OnboardingSemesterRouteImport } from './routes/onboarding/semester'
import { Route as OnboardingPhotosRouteImport } from './routes/onboarding/photos'
import { Route as OnboardingNameRouteImport } from './routes/onboarding/name'
import { Route as OnboardingLookingForRouteImport } from './routes/onboarding/looking-for'
import { Route as OnboardingInterestsRouteImport } from './routes/onboarding/interests'
import { Route as OnboardingGraduationYearRouteImport } from './routes/onboarding/graduation-year'
import { Route as OnboardingGenderRouteImport } from './routes/onboarding/gender'
import { Route as OnboardingDepartmentRouteImport } from './routes/onboarding/department'
import { Route as OnboardingDateOfBirthRouteImport } from './routes/onboarding/date-of-birth'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingCollegeRouteImport } from './routes/onboarding/college'
import { Route as OnboardingBioRouteImport } from './routes/onboarding/bio'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCommunityGuidelinesRouteImport } from './routes/_public/community-guidelines'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AuthenticatedMatchesRouteImport } from './routes/_authenticated/matches'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches.index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home.index'
import { Route as AuthenticatedDiscoverIndexRouteImport } from './routes/_authenticated/discover.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiPublicPushRouteImport } from './routes/api/public/push'
import { Route as AuthenticatedMatchesMatchIdRouteImport } from './routes/_authenticated/matches.$matchId'
import { Route as AuthenticatedHomeCollegeRankingsRouteImport } from './routes/_authenticated/home.college-rankings'
import { Route as AuthenticatedDiscoverNoMoreProfilesRouteImport } from './routes/_authenticated/discover.no-more-profiles'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'
import { Route as AuthenticatedMatchesMatchIdUnmatchRouteImport } from './routes/_authenticated/matches.$matchId.unmatch'
import { Route as AuthenticatedMatchesMatchIdReportRouteImport } from './routes/_authenticated/matches.$matchId.report'
import { Route as AuthenticatedMatchesMatchIdNoteRouteImport } from './routes/_authenticated/matches.$matchId.note'
import { Route as AuthenticatedMatchesMatchIdChatRouteImport } from './routes/_authenticated/matches.$matchId.chat'
import { Route as AuthenticatedMatchesMatchIdBlockRouteImport } from './routes/_authenticated/matches.$matchId.block'
import { Route as AuthenticatedHomeCollegeCollegeIdRouteImport } from './routes/_authenticated/home.college.$collegeId'
import { Route as AuthenticatedDiscoverProfileUserIdRouteImport } from './routes/_authenticated/discover.profile.$userId'
import { Route as AuthenticatedDiscoverMatchMatchIdRouteImport } from './routes/_authenticated/discover.match.$matchId'
import { Route as AuthenticatedChatChatIdReportRouteImport } from './routes/_authenticated/chat.$chatId.report'
import { Route as AuthenticatedChatChatIdMediaRouteImport } from './routes/_authenticated/chat.$chatId.media'
import { Route as AuthenticatedChatChatIdInfoRouteImport } from './routes/_authenticated/chat.$chatId.info'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const SystemSplashRoute = SystemSplashRouteImport.update({
  id: '/system/splash',
  path: '/system/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMaintenanceRoute = SystemMaintenanceRouteImport.update({
  id: '/system/maintenance',
  path: '/system/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSemesterRoute = OnboardingSemesterRouteImport.update({
  id: '/semester',
  path: '/semester',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingPhotosRoute = OnboardingPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingNameRoute = OnboardingNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingLookingForRoute = OnboardingLookingForRouteImport.update({
  id: '/looking-for',
  path: '/looking-for',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingInterestsRoute = OnboardingInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingGraduationYearRoute =
  OnboardingGraduationYearRouteImport.update({
    id: '/graduation-year',
    path: '/graduation-year',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const OnboardingGenderRoute = OnboardingGenderRouteImport.update({
  id: '/gender',
  path: '/gender',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDepartmentRoute = OnboardingDepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingDateOfBirthRoute = OnboardingDateOfBirthRouteImport.update({
  id: '/date-of-birth',
  path: '/date-of-birth',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCollegeRoute = OnboardingCollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingBioRoute = OnboardingBioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCommunityGuidelinesRoute =
  PublicCommunityGuidelinesRouteImport.update({
    id: '/community-guidelines',
    path: '/community-guidelines',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedMatchesRoute = AuthenticatedMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHomeRoute,
} as any)
const AuthenticatedDiscoverIndexRoute =
  AuthenticatedDiscoverIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDiscoverRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const ApiPublicPushRoute = ApiPublicPushRouteImport.update({
  id: '/api/public/push',
  path: '/api/public/push',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMatchesMatchIdRoute =
  AuthenticatedMatchesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedMatchesRoute,
  } as any)
const AuthenticatedHomeCollegeRankingsRoute =
  AuthenticatedHomeCollegeRankingsRouteImport.update({
    id: '/college-rankings',
    path: '/college-rankings',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedDiscoverNoMoreProfilesRoute =
  AuthenticatedDiscoverNoMoreProfilesRouteImport.update({
    id: '/no-more-profiles',
    path: '/no-more-profiles',
    getParentRoute: () => AuthenticatedDiscoverRoute,
  } as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedMatchesMatchIdUnmatchRoute =
  AuthenticatedMatchesMatchIdUnmatchRouteImport.update({
    id: '/unmatch',
    path: '/unmatch',
    getParentRoute: () => AuthenticatedMatchesMatchIdRoute,
  } as any)
const AuthenticatedMatchesMatchIdReportRoute =
  AuthenticatedMatchesMatchIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedMatchesMatchIdRoute,
  } as any)
const AuthenticatedMatchesMatchIdNoteRoute =
  AuthenticatedMatchesMatchIdNoteRouteImport.update({
    id: '/note',
    path: '/note',
    getParentRoute: () => AuthenticatedMatchesMatchIdRoute,
  } as any)
const AuthenticatedMatchesMatchIdChatRoute =
  AuthenticatedMatchesMatchIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedMatchesMatchIdRoute,
  } as any)
const AuthenticatedMatchesMatchIdBlockRoute =
  AuthenticatedMatchesMatchIdBlockRouteImport.update({
    id: '/block',
    path: '/block',
    getParentRoute: () => AuthenticatedMatchesMatchIdRoute,
  } as any)
const AuthenticatedHomeCollegeCollegeIdRoute =
  AuthenticatedHomeCollegeCollegeIdRouteImport.update({
    id: '/college/$collegeId',
    path: '/college/$collegeId',
    getParentRoute: () => AuthenticatedHomeRoute,
  } as any)
const AuthenticatedDiscoverProfileUserIdRoute =
  AuthenticatedDiscoverProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedDiscoverRoute,
  } as any)
const AuthenticatedDiscoverMatchMatchIdRoute =
  AuthenticatedDiscoverMatchMatchIdRouteImport.update({
    id: '/match/$matchId',
    path: '/match/$matchId',
    getParentRoute: () => AuthenticatedDiscoverRoute,
  } as any)
const AuthenticatedChatChatIdReportRoute =
  AuthenticatedChatChatIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedChatChatIdRoute,
  } as any)
const AuthenticatedChatChatIdMediaRoute =
  AuthenticatedChatChatIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedChatChatIdRoute,
  } as any)
const AuthenticatedChatChatIdInfoRoute =
  AuthenticatedChatChatIdInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () => AuthenticatedChatChatIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/auth': typeof AuthRouteWithChildren
  '/ui': typeof UiRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/discover': typeof AuthenticatedDiscoverRouteWithChildren
  '/home': typeof AuthenticatedHomeRouteWithChildren
  '/matches': typeof AuthenticatedMatchesRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/community-guidelines': typeof PublicCommunityGuidelinesRoute
  '/contact': typeof PublicContactRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/onboarding/bio': typeof OnboardingBioRoute
  '/onboarding/college': typeof OnboardingCollegeRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/date-of-birth': typeof OnboardingDateOfBirthRoute
  '/onboarding/department': typeof OnboardingDepartmentRoute
  '/onboarding/gender': typeof OnboardingGenderRoute
  '/onboarding/graduation-year': typeof OnboardingGraduationYearRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/looking-for': typeof OnboardingLookingForRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/photos': typeof OnboardingPhotosRoute
  '/onboarding/semester': typeof OnboardingSemesterRoute
  '/system/maintenance': typeof SystemMaintenanceRoute
  '/system/splash': typeof SystemSplashRoute
  '/auth/': typeof AuthIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRouteWithChildren
  '/discover/no-more-profiles': typeof AuthenticatedDiscoverNoMoreProfilesRoute
  '/home/college-rankings': typeof AuthenticatedHomeCollegeRankingsRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRouteWithChildren
  '/api/public/push': typeof ApiPublicPushRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/discover/': typeof AuthenticatedDiscoverIndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/chat/$chatId/info': typeof AuthenticatedChatChatIdInfoRoute
  '/chat/$chatId/media': typeof AuthenticatedChatChatIdMediaRoute
  '/chat/$chatId/report': typeof AuthenticatedChatChatIdReportRoute
  '/discover/match/$matchId': typeof AuthenticatedDiscoverMatchMatchIdRoute
  '/discover/profile/$userId': typeof AuthenticatedDiscoverProfileUserIdRoute
  '/home/college/$collegeId': typeof AuthenticatedHomeCollegeCollegeIdRoute
  '/matches/$matchId/block': typeof AuthenticatedMatchesMatchIdBlockRoute
  '/matches/$matchId/chat': typeof AuthenticatedMatchesMatchIdChatRoute
  '/matches/$matchId/note': typeof AuthenticatedMatchesMatchIdNoteRoute
  '/matches/$matchId/report': typeof AuthenticatedMatchesMatchIdReportRoute
  '/matches/$matchId/unmatch': typeof AuthenticatedMatchesMatchIdUnmatchRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/ui': typeof UiRoute
  '/about': typeof PublicAboutRoute
  '/community-guidelines': typeof PublicCommunityGuidelinesRoute
  '/contact': typeof PublicContactRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/onboarding/bio': typeof OnboardingBioRoute
  '/onboarding/college': typeof OnboardingCollegeRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/date-of-birth': typeof OnboardingDateOfBirthRoute
  '/onboarding/department': typeof OnboardingDepartmentRoute
  '/onboarding/gender': typeof OnboardingGenderRoute
  '/onboarding/graduation-year': typeof OnboardingGraduationYearRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/looking-for': typeof OnboardingLookingForRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/photos': typeof OnboardingPhotosRoute
  '/onboarding/semester': typeof OnboardingSemesterRoute
  '/system/maintenance': typeof SystemMaintenanceRoute
  '/system/splash': typeof SystemSplashRoute
  '/auth': typeof AuthIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRouteWithChildren
  '/discover/no-more-profiles': typeof AuthenticatedDiscoverNoMoreProfilesRoute
  '/home/college-rankings': typeof AuthenticatedHomeCollegeRankingsRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRouteWithChildren
  '/api/public/push': typeof ApiPublicPushRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/discover': typeof AuthenticatedDiscoverIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/chat/$chatId/info': typeof AuthenticatedChatChatIdInfoRoute
  '/chat/$chatId/media': typeof AuthenticatedChatChatIdMediaRoute
  '/chat/$chatId/report': typeof AuthenticatedChatChatIdReportRoute
  '/discover/match/$matchId': typeof AuthenticatedDiscoverMatchMatchIdRoute
  '/discover/profile/$userId': typeof AuthenticatedDiscoverProfileUserIdRoute
  '/home/college/$collegeId': typeof AuthenticatedHomeCollegeCollegeIdRoute
  '/matches/$matchId/block': typeof AuthenticatedMatchesMatchIdBlockRoute
  '/matches/$matchId/chat': typeof AuthenticatedMatchesMatchIdChatRoute
  '/matches/$matchId/note': typeof AuthenticatedMatchesMatchIdNoteRoute
  '/matches/$matchId/report': typeof AuthenticatedMatchesMatchIdReportRoute
  '/matches/$matchId/unmatch': typeof AuthenticatedMatchesMatchIdUnmatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/auth': typeof AuthRouteWithChildren
  '/ui': typeof UiRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/discover': typeof AuthenticatedDiscoverRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRouteWithChildren
  '/_authenticated/matches': typeof AuthenticatedMatchesRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/community-guidelines': typeof PublicCommunityGuidelinesRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/onboarding/bio': typeof OnboardingBioRoute
  '/onboarding/college': typeof OnboardingCollegeRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/date-of-birth': typeof OnboardingDateOfBirthRoute
  '/onboarding/department': typeof OnboardingDepartmentRoute
  '/onboarding/gender': typeof OnboardingGenderRoute
  '/onboarding/graduation-year': typeof OnboardingGraduationYearRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/looking-for': typeof OnboardingLookingForRoute
  '/onboarding/name': typeof OnboardingNameRoute
  '/onboarding/photos': typeof OnboardingPhotosRoute
  '/onboarding/semester': typeof OnboardingSemesterRoute
  '/system/maintenance': typeof SystemMaintenanceRoute
  '/system/splash': typeof SystemSplashRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRouteWithChildren
  '/_authenticated/discover/no-more-profiles': typeof AuthenticatedDiscoverNoMoreProfilesRoute
  '/_authenticated/home/college-rankings': typeof AuthenticatedHomeCollegeRankingsRoute
  '/_authenticated/matches/$matchId': typeof AuthenticatedMatchesMatchIdRouteWithChildren
  '/api/public/push': typeof ApiPublicPushRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/discover/': typeof AuthenticatedDiscoverIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/chat/$chatId/info': typeof AuthenticatedChatChatIdInfoRoute
  '/_authenticated/chat/$chatId/media': typeof AuthenticatedChatChatIdMediaRoute
  '/_authenticated/chat/$chatId/report': typeof AuthenticatedChatChatIdReportRoute
  '/_authenticated/discover/match/$matchId': typeof AuthenticatedDiscoverMatchMatchIdRoute
  '/_authenticated/discover/profile/$userId': typeof AuthenticatedDiscoverProfileUserIdRoute
  '/_authenticated/home/college/$collegeId': typeof AuthenticatedHomeCollegeCollegeIdRoute
  '/_authenticated/matches/$matchId/block': typeof AuthenticatedMatchesMatchIdBlockRoute
  '/_authenticated/matches/$matchId/chat': typeof AuthenticatedMatchesMatchIdChatRoute
  '/_authenticated/matches/$matchId/note': typeof AuthenticatedMatchesMatchIdNoteRoute
  '/_authenticated/matches/$matchId/report': typeof AuthenticatedMatchesMatchIdReportRoute
  '/_authenticated/matches/$matchId/unmatch': typeof AuthenticatedMatchesMatchIdUnmatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/404'
    | '/500'
    | '/auth'
    | '/ui'
    | '/chat'
    | '/discover'
    | '/home'
    | '/matches'
    | '/about'
    | '/community-guidelines'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/onboarding/bio'
    | '/onboarding/college'
    | '/onboarding/complete'
    | '/onboarding/date-of-birth'
    | '/onboarding/department'
    | '/onboarding/gender'
    | '/onboarding/graduation-year'
    | '/onboarding/interests'
    | '/onboarding/looking-for'
    | '/onboarding/name'
    | '/onboarding/photos'
    | '/onboarding/semester'
    | '/system/maintenance'
    | '/system/splash'
    | '/auth/'
    | '/onboarding/'
    | '/chat/$chatId'
    | '/discover/no-more-profiles'
    | '/home/college-rankings'
    | '/matches/$matchId'
    | '/api/public/push'
    | '/chat/'
    | '/discover/'
    | '/home/'
    | '/matches/'
    | '/chat/$chatId/info'
    | '/chat/$chatId/media'
    | '/chat/$chatId/report'
    | '/discover/match/$matchId'
    | '/discover/profile/$userId'
    | '/home/college/$collegeId'
    | '/matches/$matchId/block'
    | '/matches/$matchId/chat'
    | '/matches/$matchId/note'
    | '/matches/$matchId/report'
    | '/matches/$matchId/unmatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/500'
    | '/ui'
    | '/about'
    | '/community-guidelines'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/onboarding/bio'
    | '/onboarding/college'
    | '/onboarding/complete'
    | '/onboarding/date-of-birth'
    | '/onboarding/department'
    | '/onboarding/gender'
    | '/onboarding/graduation-year'
    | '/onboarding/interests'
    | '/onboarding/looking-for'
    | '/onboarding/name'
    | '/onboarding/photos'
    | '/onboarding/semester'
    | '/system/maintenance'
    | '/system/splash'
    | '/auth'
    | '/onboarding'
    | '/chat/$chatId'
    | '/discover/no-more-profiles'
    | '/home/college-rankings'
    | '/matches/$matchId'
    | '/api/public/push'
    | '/chat'
    | '/discover'
    | '/home'
    | '/matches'
    | '/chat/$chatId/info'
    | '/chat/$chatId/media'
    | '/chat/$chatId/report'
    | '/discover/match/$matchId'
    | '/discover/profile/$userId'
    | '/home/college/$collegeId'
    | '/matches/$matchId/block'
    | '/matches/$matchId/chat'
    | '/matches/$matchId/note'
    | '/matches/$matchId/report'
    | '/matches/$matchId/unmatch'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/onboarding'
    | '/404'
    | '/500'
    | '/auth'
    | '/ui'
    | '/_authenticated/chat'
    | '/_authenticated/discover'
    | '/_authenticated/home'
    | '/_authenticated/matches'
    | '/_public/about'
    | '/_public/community-guidelines'
    | '/_public/contact'
    | '/_public/privacy'
    | '/_public/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-otp'
    | '/onboarding/bio'
    | '/onboarding/college'
    | '/onboarding/complete'
    | '/onboarding/date-of-birth'
    | '/onboarding/department'
    | '/onboarding/gender'
    | '/onboarding/graduation-year'
    | '/onboarding/interests'
    | '/onboarding/looking-for'
    | '/onboarding/name'
    | '/onboarding/photos'
    | '/onboarding/semester'
    | '/system/maintenance'
    | '/system/splash'
    | '/_public/'
    | '/auth/'
    | '/onboarding/'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/discover/no-more-profiles'
    | '/_authenticated/home/college-rankings'
    | '/_authenticated/matches/$matchId'
    | '/api/public/push'
    | '/_authenticated/chat/'
    | '/_authenticated/discover/'
    | '/_authenticated/home/'
    | '/_authenticated/matches/'
    | '/_authenticated/chat/$chatId/info'
    | '/_authenticated/chat/$chatId/media'
    | '/_authenticated/chat/$chatId/report'
    | '/_authenticated/discover/match/$matchId'
    | '/_authenticated/discover/profile/$userId'
    | '/_authenticated/home/college/$collegeId'
    | '/_authenticated/matches/$matchId/block'
    | '/_authenticated/matches/$matchId/chat'
    | '/_authenticated/matches/$matchId/note'
    | '/_authenticated/matches/$matchId/report'
    | '/_authenticated/matches/$matchId/unmatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AuthRoute: typeof AuthRouteWithChildren
  UiRoute: typeof UiRoute
  SystemMaintenanceRoute: typeof SystemMaintenanceRoute
  SystemSplashRoute: typeof SystemSplashRoute
  ApiPublicPushRoute: typeof ApiPublicPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/system/splash': {
      id: '/system/splash'
      path: '/system/splash'
      fullPath: '/system/splash'
      preLoaderRoute: typeof SystemSplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/maintenance': {
      id: '/system/maintenance'
      path: '/system/maintenance'
      fullPath: '/system/maintenance'
      preLoaderRoute: typeof SystemMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/semester': {
      id: '/onboarding/semester'
      path: '/semester'
      fullPath: '/onboarding/semester'
      preLoaderRoute: typeof OnboardingSemesterRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/photos': {
      id: '/onboarding/photos'
      path: '/photos'
      fullPath: '/onboarding/photos'
      preLoaderRoute: typeof OnboardingPhotosRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/name': {
      id: '/onboarding/name'
      path: '/name'
      fullPath: '/onboarding/name'
      preLoaderRoute: typeof OnboardingNameRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/looking-for': {
      id: '/onboarding/looking-for'
      path: '/looking-for'
      fullPath: '/onboarding/looking-for'
      preLoaderRoute: typeof OnboardingLookingForRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/interests': {
      id: '/onboarding/interests'
      path: '/interests'
      fullPath: '/onboarding/interests'
      preLoaderRoute: typeof OnboardingInterestsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/graduation-year': {
      id: '/onboarding/graduation-year'
      path: '/graduation-year'
      fullPath: '/onboarding/graduation-year'
      preLoaderRoute: typeof OnboardingGraduationYearRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/gender': {
      id: '/onboarding/gender'
      path: '/gender'
      fullPath: '/onboarding/gender'
      preLoaderRoute: typeof OnboardingGenderRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/department': {
      id: '/onboarding/department'
      path: '/department'
      fullPath: '/onboarding/department'
      preLoaderRoute: typeof OnboardingDepartmentRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/date-of-birth': {
      id: '/onboarding/date-of-birth'
      path: '/date-of-birth'
      fullPath: '/onboarding/date-of-birth'
      preLoaderRoute: typeof OnboardingDateOfBirthRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/college': {
      id: '/onboarding/college'
      path: '/college'
      fullPath: '/onboarding/college'
      preLoaderRoute: typeof OnboardingCollegeRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/bio': {
      id: '/onboarding/bio'
      path: '/bio'
      fullPath: '/onboarding/bio'
      preLoaderRoute: typeof OnboardingBioRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/community-guidelines': {
      id: '/_public/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof PublicCommunityGuidelinesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/matches': {
      id: '/_authenticated/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/discover/': {
      id: '/_authenticated/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof AuthenticatedDiscoverIndexRouteImport
      parentRoute: typeof AuthenticatedDiscoverRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/public/push': {
      id: '/api/public/push'
      path: '/api/public/push'
      fullPath: '/api/public/push'
      preLoaderRoute: typeof ApiPublicPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/matches/$matchId': {
      id: '/_authenticated/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedMatchesRoute
    }
    '/_authenticated/home/college-rankings': {
      id: '/_authenticated/home/college-rankings'
      path: '/college-rankings'
      fullPath: '/home/college-rankings'
      preLoaderRoute: typeof AuthenticatedHomeCollegeRankingsRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/discover/no-more-profiles': {
      id: '/_authenticated/discover/no-more-profiles'
      path: '/no-more-profiles'
      fullPath: '/discover/no-more-profiles'
      preLoaderRoute: typeof AuthenticatedDiscoverNoMoreProfilesRouteImport
      parentRoute: typeof AuthenticatedDiscoverRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/matches/$matchId/unmatch': {
      id: '/_authenticated/matches/$matchId/unmatch'
      path: '/unmatch'
      fullPath: '/matches/$matchId/unmatch'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdUnmatchRouteImport
      parentRoute: typeof AuthenticatedMatchesMatchIdRoute
    }
    '/_authenticated/matches/$matchId/report': {
      id: '/_authenticated/matches/$matchId/report'
      path: '/report'
      fullPath: '/matches/$matchId/report'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdReportRouteImport
      parentRoute: typeof AuthenticatedMatchesMatchIdRoute
    }
    '/_authenticated/matches/$matchId/note': {
      id: '/_authenticated/matches/$matchId/note'
      path: '/note'
      fullPath: '/matches/$matchId/note'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdNoteRouteImport
      parentRoute: typeof AuthenticatedMatchesMatchIdRoute
    }
    '/_authenticated/matches/$matchId/chat': {
      id: '/_authenticated/matches/$matchId/chat'
      path: '/chat'
      fullPath: '/matches/$matchId/chat'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdChatRouteImport
      parentRoute: typeof AuthenticatedMatchesMatchIdRoute
    }
    '/_authenticated/matches/$matchId/block': {
      id: '/_authenticated/matches/$matchId/block'
      path: '/block'
      fullPath: '/matches/$matchId/block'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdBlockRouteImport
      parentRoute: typeof AuthenticatedMatchesMatchIdRoute
    }
    '/_authenticated/home/college/$collegeId': {
      id: '/_authenticated/home/college/$collegeId'
      path: '/college/$collegeId'
      fullPath: '/home/college/$collegeId'
      preLoaderRoute: typeof AuthenticatedHomeCollegeCollegeIdRouteImport
      parentRoute: typeof AuthenticatedHomeRoute
    }
    '/_authenticated/discover/profile/$userId': {
      id: '/_authenticated/discover/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/discover/profile/$userId'
      preLoaderRoute: typeof AuthenticatedDiscoverProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedDiscoverRoute
    }
    '/_authenticated/discover/match/$matchId': {
      id: '/_authenticated/discover/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/discover/match/$matchId'
      preLoaderRoute: typeof AuthenticatedDiscoverMatchMatchIdRouteImport
      parentRoute: typeof AuthenticatedDiscoverRoute
    }
    '/_authenticated/chat/$chatId/report': {
      id: '/_authenticated/chat/$chatId/report'
      path: '/report'
      fullPath: '/chat/$chatId/report'
      preLoaderRoute: typeof AuthenticatedChatChatIdReportRouteImport
      parentRoute: typeof AuthenticatedChatChatIdRoute
    }
    '/_authenticated/chat/$chatId/media': {
      id: '/_authenticated/chat/$chatId/media'
      path: '/media'
      fullPath: '/chat/$chatId/media'
      preLoaderRoute: typeof AuthenticatedChatChatIdMediaRouteImport
      parentRoute: typeof AuthenticatedChatChatIdRoute
    }
    '/_authenticated/chat/$chatId/info': {
      id: '/_authenticated/chat/$chatId/info'
      path: '/info'
      fullPath: '/chat/$chatId/info'
      preLoaderRoute: typeof AuthenticatedChatChatIdInfoRouteImport
      parentRoute: typeof AuthenticatedChatChatIdRoute
    }
  }
}

interface AuthenticatedChatChatIdRouteChildren {
  AuthenticatedChatChatIdInfoRoute: typeof AuthenticatedChatChatIdInfoRoute
  AuthenticatedChatChatIdMediaRoute: typeof AuthenticatedChatChatIdMediaRoute
  AuthenticatedChatChatIdReportRoute: typeof AuthenticatedChatChatIdReportRoute
}

const AuthenticatedChatChatIdRouteChildren: AuthenticatedChatChatIdRouteChildren =
  {
    AuthenticatedChatChatIdInfoRoute: AuthenticatedChatChatIdInfoRoute,
    AuthenticatedChatChatIdMediaRoute: AuthenticatedChatChatIdMediaRoute,
    AuthenticatedChatChatIdReportRoute: AuthenticatedChatChatIdReportRoute,
  }

const AuthenticatedChatChatIdRouteWithChildren =
  AuthenticatedChatChatIdRoute._addFileChildren(
    AuthenticatedChatChatIdRouteChildren,
  )

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRouteWithChildren
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRouteWithChildren,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedDiscoverRouteChildren {
  AuthenticatedDiscoverNoMoreProfilesRoute: typeof AuthenticatedDiscoverNoMoreProfilesRoute
  AuthenticatedDiscoverIndexRoute: typeof AuthenticatedDiscoverIndexRoute
  AuthenticatedDiscoverMatchMatchIdRoute: typeof AuthenticatedDiscoverMatchMatchIdRoute
  AuthenticatedDiscoverProfileUserIdRoute: typeof AuthenticatedDiscoverProfileUserIdRoute
}

const AuthenticatedDiscoverRouteChildren: AuthenticatedDiscoverRouteChildren = {
  AuthenticatedDiscoverNoMoreProfilesRoute:
    AuthenticatedDiscoverNoMoreProfilesRoute,
  AuthenticatedDiscoverIndexRoute: AuthenticatedDiscoverIndexRoute,
  AuthenticatedDiscoverMatchMatchIdRoute:
    AuthenticatedDiscoverMatchMatchIdRoute,
  AuthenticatedDiscoverProfileUserIdRoute:
    AuthenticatedDiscoverProfileUserIdRoute,
}

const AuthenticatedDiscoverRouteWithChildren =
  AuthenticatedDiscoverRoute._addFileChildren(
    AuthenticatedDiscoverRouteChildren,
  )

interface AuthenticatedHomeRouteChildren {
  AuthenticatedHomeCollegeRankingsRoute: typeof AuthenticatedHomeCollegeRankingsRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedHomeCollegeCollegeIdRoute: typeof AuthenticatedHomeCollegeCollegeIdRoute
}

const AuthenticatedHomeRouteChildren: AuthenticatedHomeRouteChildren = {
  AuthenticatedHomeCollegeRankingsRoute: AuthenticatedHomeCollegeRankingsRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedHomeCollegeCollegeIdRoute:
    AuthenticatedHomeCollegeCollegeIdRoute,
}

const AuthenticatedHomeRouteWithChildren =
  AuthenticatedHomeRoute._addFileChildren(AuthenticatedHomeRouteChildren)

interface AuthenticatedMatchesMatchIdRouteChildren {
  AuthenticatedMatchesMatchIdBlockRoute: typeof AuthenticatedMatchesMatchIdBlockRoute
  AuthenticatedMatchesMatchIdChatRoute: typeof AuthenticatedMatchesMatchIdChatRoute
  AuthenticatedMatchesMatchIdNoteRoute: typeof AuthenticatedMatchesMatchIdNoteRoute
  AuthenticatedMatchesMatchIdReportRoute: typeof AuthenticatedMatchesMatchIdReportRoute
  AuthenticatedMatchesMatchIdUnmatchRoute: typeof AuthenticatedMatchesMatchIdUnmatchRoute
}

const AuthenticatedMatchesMatchIdRouteChildren: AuthenticatedMatchesMatchIdRouteChildren =
  {
    AuthenticatedMatchesMatchIdBlockRoute:
      AuthenticatedMatchesMatchIdBlockRoute,
    AuthenticatedMatchesMatchIdChatRoute: AuthenticatedMatchesMatchIdChatRoute,
    AuthenticatedMatchesMatchIdNoteRoute: AuthenticatedMatchesMatchIdNoteRoute,
    AuthenticatedMatchesMatchIdReportRoute:
      AuthenticatedMatchesMatchIdReportRoute,
    AuthenticatedMatchesMatchIdUnmatchRoute:
      AuthenticatedMatchesMatchIdUnmatchRoute,
  }

const AuthenticatedMatchesMatchIdRouteWithChildren =
  AuthenticatedMatchesMatchIdRoute._addFileChildren(
    AuthenticatedMatchesMatchIdRouteChildren,
  )

interface AuthenticatedMatchesRouteChildren {
  AuthenticatedMatchesMatchIdRoute: typeof AuthenticatedMatchesMatchIdRouteWithChildren
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
}

const AuthenticatedMatchesRouteChildren: AuthenticatedMatchesRouteChildren = {
  AuthenticatedMatchesMatchIdRoute:
    AuthenticatedMatchesMatchIdRouteWithChildren,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
}

const AuthenticatedMatchesRouteWithChildren =
  AuthenticatedMatchesRoute._addFileChildren(AuthenticatedMatchesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRouteWithChildren
  AuthenticatedMatchesRoute: typeof AuthenticatedMatchesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRouteWithChildren,
  AuthenticatedMatchesRoute: AuthenticatedMatchesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCommunityGuidelinesRoute: typeof PublicCommunityGuidelinesRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCommunityGuidelinesRoute: PublicCommunityGuidelinesRoute,
  PublicContactRoute: PublicContactRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingBioRoute: typeof OnboardingBioRoute
  OnboardingCollegeRoute: typeof OnboardingCollegeRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingDateOfBirthRoute: typeof OnboardingDateOfBirthRoute
  OnboardingDepartmentRoute: typeof OnboardingDepartmentRoute
  OnboardingGenderRoute: typeof OnboardingGenderRoute
  OnboardingGraduationYearRoute: typeof OnboardingGraduationYearRoute
  OnboardingInterestsRoute: typeof OnboardingInterestsRoute
  OnboardingLookingForRoute: typeof OnboardingLookingForRoute
  OnboardingNameRoute: typeof OnboardingNameRoute
  OnboardingPhotosRoute: typeof OnboardingPhotosRoute
  OnboardingSemesterRoute: typeof OnboardingSemesterRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingBioRoute: OnboardingBioRoute,
  OnboardingCollegeRoute: OnboardingCollegeRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingDateOfBirthRoute: OnboardingDateOfBirthRoute,
  OnboardingDepartmentRoute: OnboardingDepartmentRoute,
  OnboardingGenderRoute: OnboardingGenderRoute,
  OnboardingGraduationYearRoute: OnboardingGraduationYearRoute,
  OnboardingInterestsRoute: OnboardingInterestsRoute,
  OnboardingLookingForRoute: OnboardingLookingForRoute,
  OnboardingNameRoute: OnboardingNameRoute,
  OnboardingPhotosRoute: OnboardingPhotosRoute,
  OnboardingSemesterRoute: OnboardingSemesterRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  R404Route: R404Route,
  R500Route: R500Route,
  AuthRoute: AuthRouteWithChildren,
  UiRoute: UiRoute,
  SystemMaintenanceRoute: SystemMaintenanceRoute,
  SystemSplashRoute: SystemSplashRoute,
  ApiPublicPushRoute: ApiPublicPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
