// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlclayiqmsxxssmgpfej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsY2xheWlxbXN4eHNzbWdwZmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4NDU4NzIsImV4cCI6MjA5OTQyMTg3Mn0.8r5VnVj-Qwoaz8_mq9RSa0cwCw5hK0IKRhhHAm5TDp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});